spring.application.name=my-market-app

# Connection Pool
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20

# Thymeleaf
spring.thymeleaf.cache=false
# spring.thymeleaf.prefix=classpath:/templates/
# spring.thymeleaf.suffix=.html

# Static Resources
spring.webflux.static-path-pattern=/**
spring.webflux.static-locations=classpath:/static/

# Encoding
server.tomcat.uri-encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=5s
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

app.cache.item-ttl=5
spring.cache.type=redis
spring.cache.redis.time-to-live=300000
spring.cache.redis.cache-null-values=false
spring.cache.redis.key-prefix=my-market:cache:

# Payment service
payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8081}

# Spring Security
spring.main.allow-bean-definition-overriding=true

# Keycloak configuration
spring.security.oauth2.client.registration.keycloak.client-id=my-market-app
spring.security.oauth2.client.registration.keycloak.client-secret=JIDckaVoJBaQXz14hmv9cnqVW28yrSqt
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8082/realms/master
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

# Resource server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/master

# Logging
logging.level.ru.yandex.practicum.mymarket=DEBUG
logging.level.org.springframework.data.r2dbc=DEBUG
logging.level.io.r2dbc=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.ru.yandex.practicum.mymarket.service.ItemCacheService=DEBUG
logging.level.ru.yandex.practicum.mymarket.service.ItemService=DEBUG
logging.level.org.springframework.data.redis=DEBUG