spring.application.name=my-market-app

# Connection Pool
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Static Resources
spring.webflux.static-path-pattern=/**
spring.webflux.static-locations=classpath:/static/

# Encoding
server.tomcat.uri-encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# Logging
logging.level.ru.yandex.practicum.mymarket=DEBUG
logging.level.org.springframework.data.r2dbc=DEBUG
logging.level.io.r2dbc=DEBUG
logging.level.org.springframework.web=DEBUG