spring.application.name=payment-service
server.port=8081

payment.initial-balance=100000

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/master

logging.level.ru.yandex.practicum.payment=DEBUG